### PR TITLE
restore pod level log collection per namespace

### PR DESCRIPTION
**Pull request by SeanMooney**
this restores the previous log collection behavior
without preventing extended logs to be colelcted via sos_reports

### CODE REVIEW

**Review by fmount — COMMENTED** [review]
/lgtm

**Review by Akrog — CHANGES_REQUESTED** [review]
This should be conditional and disabled by default, since customer cases that should have the sos report should not need to retrieve this logs as they are already under /var/log/pods

**Comment by fmount** [comment]
> This should be conditional and disabled by default, since customer cases that should have the sos report should not need to retrieve this logs as they are already under /var/log/pods

can we do that in a follow up?

**Comment by stuggi** [comment]
> > This should be conditional and disabled by default, since customer cases that should have the sos report should not need to retrieve this logs as they are already under /var/log/pods
> 
> can we do that in a follow up? I would do that conditionally and disabled based on the SOS behavior, but I'm ok to do that with > 1 PR. By merging this every single upstream CI run can benefit of this part (and they're mostly single node / crc deployments)

As discussed with @fmount in slack, I had a situation where we gathered logs and sosreport retrieval failed for all nodes.

```
[must-gather-qnc6t] POD error: UntilWithSync: unable to sync caches: context deadline exceeded
[must-gather-qnc6t] POD Failed to run sos report on node ooo-node3, won't retrieve data
```

as a result we ended up with no pod logs at all. I think we should always gather the pod logs with the OCP default way and in addition when sosreports were gathered have more logs

**Comment by fmount** [comment]
I tested this patch locally and I'm still inclined to merge, and unstuck some troubleshooting for a CU.
We'll open bugs and discuss more about the long term plan w/ sos and api log collection, but for now I'd like to restore this behavior.

**Comment by rebtoor** [comment]
this would be useful for CI as well.

/lgtm

**Comment by Akrog** [comment]
I'm against this patch as it is.
openstack-must-gather is a tool primarily to gather information to debug cases from customers.
We should aim to make it user friendly for CI jobs, but we should not default to do things that make no sense on a customer (primary target).
Gathering the same logs in 2 different ways by default doesn't seem reasonable.

**Comment by fmount** [comment]
> > I'm against this patch as it is. openstack-must-gather is a tool primarily to gather information to debug cases from customers. We should aim to make it user friendly for CI jobs, but we should not default to do things that make no sense on a customer (primary target). Gathering the same logs in 2 different ways by default doesn't seem reasonable.
> 
> I'm proposing to split the sos and the api gathering. I had customers who were asked to run the tool and sos didn't work **at all**. The result is us not having logs. I do not want to gather things twice, I want to split the two use cases because I think we can't converge to the same view. I can put a conditional to this patch if it turns it to something we can merge, and follow up on the long term plan in the next few weeks.
To be clear, this is my goal:

```
oc adm must-gather --image-stream=openstack/openstack-sos-report-must-gather \
   --image-stream=openshift/must-gather \
   --image=quay.io/openstack-k8s-operators/openstack-api-must-gather:latest
```

**Comment by Akrog** [comment]
> I'm proposing to split the sos and the api gathering. I had customers who were asked to run the tool and sos didn't work **at all**. The result is us not having logs. I do not want to gather things twice, I want to split the two use cases because I think we can't converge to the same view. I can put a conditional to this patch if it turns it to something we can merge, and follow up on the long term plan in the next few weeks. This might be the long term goal:

Those are 2 different matters to me:

- If SOS didn't work at all: We need to figure out and fix whatever is wrong there
- Splitting the gathering into 2 things is against one of the basis of what we set to do with this effort: ensure we always get all the information we want.
 
I don't know about you, but I've had many, many cases that were missing data to evaluate the issues: SOS reports only of compute nodes, service logs without the kernel messages, etc.

**Review by bshephar — APPROVED** [review]
I personally find it difficult to debug issues without this information. We should restore this, I think the information we get back from the k8s API will be the most important information when debugging control plane issues. Sosreport for me would be a secondary thing, so +1 to restoring this functionality.

**Comment by SeanMooney** [comment]
so as it stand if we don have sos report gartering reliable i think we need to proceed with this even if it means gathering things twice.

from my perspective the regression introduced by moving the gathering to sos report without that reliable working in all case is a GA blocker of a equal severity to what you originally tried to fix by making that change in the first place.

**Comment by fmount** [comment]
> > I'm proposing to split the sos and the api gathering. I had customers who were asked to run the tool and sos didn't work **at all**. The result is us not having logs. I do not want to gather things twice, I want to split the two use cases because I think we can't converge to the same view. I can put a conditional to this patch if it turns it to something we can merge, and follow up on the long term plan in the next few weeks. This might be the long term goal:
> 
> Those are 2 different matters to me:
> 
>     * If SOS didn't work at all: We need to figure out and fix whatever is wrong there
> 
>     * Splitting the gathering into 2 things is against one of the basis of what we set to do with this effort: ensure we always get all the information we want.
> 
> 
> I don't know about you, but I've had many, many cases that were missing data to evaluate the issues: SOS reports only of compute nodes, service logs without the kernel messages, etc.

Ok let me reorganize my thoughts/position on this to make sure we're on the same page:
- I'm **in** favor of a unified effort that allows to collect all the logs we need from customers/CI

- I'm **not** in favor of removing `SOS` report from the picture: my comment was mostly to check if it makes sense to have two `images` and not overload the `must-gather` `Pod` in some circumstances (see https://issues.redhat.com/browse/OSPRH-7868). Splitting for me means documenting the command as the combination of two `image-streams` that runs with two different containers, and we can still post-process and `ln -s` the result. Still one command like this:
```bash
$ oc adm must-gather --image-stream=openstack/openstack-sos-report-must-gather \
   --image-stream=openshift/must-gather \
   --image=quay.io/openstack-k8s-operators/openstack-api-must-gather:latest
```
that can be documented as a default. This way you don't need tons of conditionals in the code, and you can choose to not run what you don't need.
(Note: the image naming can be changed/simplified)

- I think that when `must-gather` is executed, we should have have a default method to get Pod logs, but not entirely exclude one or the other: sos is able to collect rotated logs, which is a valid use case, but if it fails on a customer case we still want a way to get what we need. Considering that pod logs from API is only `-current` and `-previous`, it might be useful have this information to get the very last error that prevents a Pod to start, you don't always need rotated logs 

- Given that pods are namespaced resources, I like the structure as `<namespace>/<pods>/<service>/ { description, logs/ }`. `CRDs` are global resources and already collected in the `global` section (or parent directory)

I suggest we can start with something like: `if [ "${SOS_SERVICES-unset}" = "unset" ]; then <gather pod logs from api>`. 
I definitely **want** to be able to gather all the information, and I see great value in running the SOS reports for both OCP and EDPM nodes,  I think we're on the same page on the final goal, I just think I want to:

- keep the same directory tree we previously had: : if SOS report runs, you can link rotated logs under <service>/<logs> in the same structure
- be able to gather pod logs from the API

Does `if [ "${SOS_SERVICES-unset}" = "unset" ]; then <gather pod logs from api>` would help to unblock this?

**Comment by SeanMooney** [comment]
yep i agree we shoudl still have sosreport and in ci we should also be enabling them by default
but i also beloved we should be gathering them form the API by default too and the rotated logs gathered by the sos report should be additional logs not the only way we gather pod logs when sosreport are enabled.

even if that results in duplicated logs.

**Comment by lewisdenny** [comment]
/lgtm
Folks I would like to merge this patch, in short merging this makes tomorrow better than today. 

I trust @fmount and @Akrog that this isn't the best long term solution and I would like to personally help discover and implement what that is but this PR is not the place for it imo. 

Yes the customer is a very important user of OpenStack MG but equally important is CI and Dev, we need logs to debug, everyone knows that. Let's add whatever conditions are needed in a follow up patch so when customers run MG they collect exactly how/what we want them to collect by default because I can set a 100 vars in CI in the MG role if needed... it's automated 😅

**Comment by Akrog** [comment]
@lewisdenny Who is going to do the follow up patch? Why isn't it being done here?

The right place to get the logs for CI is to add a command extract the logs as part of the CI process, not to change the code in this repo!

**Comment by Akrog** [comment]
Something like this is what I'm saying we should do for the CI: https://github.com/openstack-k8s-operators/ci-framework/pull/1941

I haven't tested that code yet, but I submitted it to illustrate my point.

**Comment by fmount** [comment]
Closing in favor of https://github.com/openstack-k8s-operators/openstack-must-gather/pull/68

**Pull request closed without merging**
