### PR TITLE
Pass ADDITIONAL_NAMESPACES when must-gathering is invoked

### PR DESCRIPTION
**Pull request by fmount**
This patch adds the ability to pass `ADDITIONAL_NAMESPACES` when the gather command is invoked. The approach is consistent with what already done with `sos reports` gathering.

### CODE REVIEW

**Comment by fmount** [comment]
Tested locally and works as expected.

**Comment by raukadah** [comment]
recheck after https://github.com/openstack-k8s-operators/ci-framework/pull/868

**Review by raukadah — COMMENTED** [review]
/lgtm

**Comment by fmount** [comment]
@lewisdenny I rebased this patch now that we have a real job and I'm expecting to see the must-gather container being rebuilt checking out the change in $subject

**Pull request merged**
